# Generated by Django 4.1.9 on 2023-05-18 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='preco')),
                ('categoria', models.CharField(max_length=100, verbose_name='categoria')),
                ('quantidade', models.CharField(max_length=100, verbose_name='quantidade')),
                ('id_barraca', models.EmailField(max_length=254, unique=True, verbose_name='email_')),
            ],
            options={
                'db_table': 'itens',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('produtor', models.BooleanField(verbose_name='podutor')),
                ('senha', models.CharField(max_length=100, verbose_name='senha')),
                ('telefone', models.CharField(max_length=100, verbose_name='telefone')),
                ('entrega', models.BooleanField(default=False, verbose_name='entrega')),
                ('rua', models.CharField(max_length=100, verbose_name='rua')),
                ('cidade', models.CharField(max_length=100, verbose_name='cidade')),
                ('cep', models.CharField(max_length=100, verbose_name='cep')),
                ('estado', models.CharField(max_length=100, verbose_name='estado')),
                ('complemento', models.CharField(max_length=100, verbose_name='complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='bairro')),
                ('numero', models.IntegerField(verbose_name='numero')),
                ('itens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itens')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
