# Generated by Django 4.1.9 on 2023-05-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barraca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(unique=True, verbose_name='usuario_')),
                ('id_itens', models.IntegerField(unique=True, verbose_name='items_')),
            ],
            options={
                'db_table': 'barraca',
            },
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_barraca', models.EmailField(max_length=254, unique=True, verbose_name='email_')),
            ],
            options={
                'db_table': 'itens',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email_')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
