# Generated by Django 4.1.9 on 2023-05-18 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itens',
            name='id_barraca',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='itens',
        ),
    ]
