# Generated by Django 4.1.9 on 2023-05-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_itens_id_barraca_remove_usuario_itens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itens',
            name='quantidade',
            field=models.IntegerField(verbose_name='quantidade'),
        ),
    ]
